- hosts: all

  tasks:
    - apt:
        name: python3-pip
        update_cache: yes
        cache_valid_time: 604800 # 1 week
      become: yes
      tags:
        - setup

    - name: Ignore PEP 668 because it's silly.
      ansible.builtin.file:
        path: /usr/lib/python3.11/EXTERNALLY-MANAGED
        state: absent
      become: yes

    - pip:
        name: docker
      become: yes
      tags:
        - setup

    - name: start redmine container
      community.docker.docker_container:
        name: redmine
        image: redmine
        published_ports: 3000:80
      become: yes
      tags:
        - redmine
