- hosts: all
  become: yes

  roles:
    - geerlingguy.pip

  tasks:
    - name: pip
      pip:
        name: docker
      tags:
        - setup
    - name: create .env
      ansible.builtin.template:
        src: template.env.j2
        dest: .env
        mode: '0644'

    - name: start redmine container
      community.docker.docker_container:
        name: redmine
        image: redmine
        published_ports: "80:{{ redmine_port }}"
        env_file: .env

- hosts: webservers
  become: yes
  tasks:
    - name: start datadog
      import_role:
        name: datadog.datadog
